export const connections = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    age: 30,
    birthDay: "1992-05-15",
    sex: "Male",
    city: "New York",
    state: "New York",
    address: "123 Main Street",
    phoneNumbers: ["123-456-7890", "987-654-3210"],
    emails: ["johndoe@example.com", "john.doe@company.com"],
    jobTitle: "Software Engineer",
  },
  {
    id: 2,
    firstName: "Jane",
    lastName: "Smith",
    age: 28,
    birthDay: "1994-09-20",
    sex: "Female",
    city: "Los Angeles",
    state: "California",
    address: "456 Elm Street",
    phoneNumbers: ["111-222-3333", "444-555-6666"],
    emails: ["jane.smith@example.com", "jane.smith@company.com"],
    jobTitle: "Marketing Manager",
  },
  {
    id: 3,
    firstName: "David",
    lastName: "Johnson",
    age: 35,
    birthDay: "1987-12-10",
    sex: "Male",
    city: "Chicago",
    state: "Illinois",
    address: "789 Oak Avenue",
    phoneNumbers: ["555-123-4567", "111-222-3333"],
    emails: ["david.johnson@example.com", "david.johnson@company.com"],
    jobTitle: "Accountant",
  },
  {
    id: 4,
    firstName: "Emily",
    lastName: "Wilson",
    age: 32,
    birthDay: "1989-06-25",
    sex: "Female",
    city: "Seattle",
    state: "Washington",
    address: "567 Pine Street",
    phoneNumbers: ["999-888-7777", "444-555-6666"],
    emails: ["emily.wilson@example.com", "emily.wilson@company.com"],
    jobTitle: "Graphic Designer",
  },
  {
    id: 5,
    firstName: "Michael",
    lastName: "Brown",
    age: 42,
    birthDay: "1979-03-12",
    sex: "Male",
    city: "Houston",
    state: "Texas",
    address: "321 Oak Street",
    phoneNumbers: ["777-888-9999", "555-444-3333"],
    emails: ["michael.brown@example.com", "michael.brown@company.com"],
    jobTitle: "Sales Manager",
  },
  {
    id: 6,
    firstName: "Sarah",
    lastName: "Johnson",
    age: 29,
    birthDay: "1994-08-18",
    sex: "Female",
    city: "Boston",
    state: "Massachusetts",
    address: "789 Elm Street",
    phoneNumbers: ["333-444-5555", "888-999-0000"],
    emails: ["sarah.johnson@example.com", "sarah.johnson@company.com"],
    jobTitle: "Software Developer",
  },
  {
    id: 7,
    firstName: "Christopher",
    lastName: "Taylor",
    age: 34,
    birthDay: "1988-09-26",
    sex: "Male",
    city: "San Francisco",
    state: "California",
    address: "123 Pine Street",
    phoneNumbers: ["222-333-4444", "555-444-3333"],
    emails: [
      "christopher.taylor@example.com",

      "christopher.taylor@company.com",
    ],
    jobTitle: "Project Manager",
  },
  {
    id: 8,
    firstName: "Emma",
    lastName: "Clark",
    age: 27,
    birthDay: "1995-06-02",
    sex: "Female",
    city: "Seattle",
    state: "Washington",
    address: "456 Oak Avenue",
    phoneNumbers: ["777-888-9999", "111-222-3333"],
    emails: ["emma.clark@example.com", "emma.clark@company.com"],
    jobTitle: "Marketing Coordinator",
  },
  {
    id: 9,
    firstName: "Jacob",
    lastName: "Robinson",
    age: 33,
    birthDay: "1989-11-15",
    sex: "Male",
    city: "Denver",
    state: "Colorado",
    address: "789 Elm Street",
    phoneNumbers: ["333-444-5555", "888-999-0000"],
    emails: ["jacob.robinson@example.com", "jacob.robinson@company.com"],
    jobTitle: "Financial Analyst",
  },
  {
    id: 10,
    firstName: "Mia",
    lastName: "Baker",
    age: 31,
    birthDay: "1991-12-10",
    sex: "Female",
    city: "Austin",
    state: "Texas",
    address: "654 Maple Lane",
    phoneNumbers: ["222-333-4444", "555-444-3333"],
    emails: ["mia.baker@example.com", "mia.baker@company.com"],
    jobTitle: "Product Manager",
  },
  {
    id: 11,
    firstName: "Liam",
    lastName: "Gonzalez",
    age: 29,
    birthDay: "1993-05-27",
    sex: "Male",
    city: "Dallas",
    state: "Texas",
    address: "987 Elm Street",
    phoneNumbers: ["333-444-5555", "888-999-0000"],
    emails: ["liam.gonzalez@example.com", "liam.gonzalez@company.com"],
    jobTitle: "Software Engineer",
  },
  {
    id: 12,
    firstName: "Charlotte",
    lastName: "Lopez",
    age: 27,
    birthDay: "1995-07-14",
    sex: "Female",
    city: "Phoenix",
    state: "Arizona",
    address: "321 Oak Street",
    phoneNumbers: ["777-888-9999", "555-444-3333"],
    emails: ["charlotte.lopez@example.com", "charlotte.lopez@company.com"],
    jobTitle: "Marketing Manager",
  },
  {
    id: 13,
    firstName: "Henry",
    lastName: "Hernandez",
    age: 35,
    birthDay: "1987-03-02",
    sex: "Male",
    city: "Miami",
    state: "Florida",
    address: "543 Pine Street",
    phoneNumbers: ["333-444-5555", "888-999-0000"],
    emails: ["henry.hernandez@example.com", "henry.hernandez@company.com"],
    jobTitle: "Sales Manager",
  },
  {
    id: 14,
    firstName: "Amelia",
    lastName: "Hall",
    age: 30,
    birthDay: "1992-10-20",
    sex: "Female",
    city: "Chicago",
    state: "Illinois",
    address: "456 Elm Street",
    phoneNumbers: ["222-333-4444", "555-444-3333"],
    emails: ["amelia.hall@example.com", "amelia.hall@company.com"],
    jobTitle: "HR Manager",
  },
  {
    id: 15,
    firstName: "William",
    lastName: "Garcia",
    age: 32,
    birthDay: "1990-12-08",
    sex: "Male",
    city: "New York",
    state: "New York",
    address: "789 Oak Avenue",
    phoneNumbers: ["777-888-9999", "111-222-3333"],
    emails: ["william.garcia@example.com", "william.garcia@company.com"],
    jobTitle: "Finance Manager",
  },
];

export default connections;
